[package]
name = "bevy_extended_ui"
version = "0.1.0"
edition = "2024"
authors = ["Daniel Ramke <genshin.exepta@outlook.com>"]

[lib]
name = "bevy_extended_ui"
path = "src/lib.rs"

[dependencies.bevy-inspector-egui]
version = "0.31.0"

[dependencies.bevy]
version = "0.16.0"
default-features = false
features = [
    "bevy_asset",
    "bevy_color",
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_text",
    "bevy_ui",
    "default_font",
    "multi_threaded",
    "png",
    "jpeg",
    "gif",
    "ico",
    "webp",
    "bevy_mesh_picking_backend",
    "bevy_picking",
    "custom_cursor",
    "bevy_ui_picking_backend",
    "bevy_winit",
    "x11",
    "bevy_log"
]

[dependencies.lightningcss]
version = "1.0.0-alpha.65"

[dependencies.once_cell]
version = "1.21.3"
[dependencies]
regex = "1.11.1"